joonan-lab/cwas

- src/simulate.py
Multiprocessing을 위해 함수 내에서 pool이 실행되었을 때, 결과물인 VCF가 모두 동일한 mutation을 가지고 있음을 확인.
함수 내에 `np.random.seed()`를 추가하여 매번 re-seed 하여 해결하고자 함.
> Commit random mutation function

- .gitignore
- cwas/core/categorization/categorizer.py
UTR are now divided into 5prime and 3prime.
> Split UTR to 5prime UTR and 3prime UTR

- cwas/annotation.py
- cwas/burden_test.py
- cwas/categorization.py
Updated codes for multiprocessing.
> Multiprocessing CWAS

- cwas/annotation.py
- cwas/argparser.py
- cwas/binomial_test.py
- cwas/burden_test.py
- cwas/categorization.py
- cwas/configuration.py
- cwas/core/annotation/vep.py
- cwas/core/categorization/categorizer.py
- cwas/core/configuration/create.py
- cwas/permutation_test.py
- cwas/preparation.py
- cwas/start.py
Previously, the format of conservation dataset was bigwig.
To enhance speed and reduce memory usage, we will change the dataset format as bed.
> Let the annotation process to get bed as conservation dataset

- cwas/argparser.py
- cwas/extract_variant.py
Add a process that can add annotation tags to variants.
> Add variant extraction process

- cwas/runnable.py
- environment.yml
1. Add perl modules (perl-dbd-sqlite, perl-db, perl-bio-db-hts) for VEP LOTFEE plugin
2. Modify `__init__` method of  `Runnable` class  to enable `_print_args` and `_check_args_validity` methods
> Update Runnable __init__ method and dependencies

- cwas/annotation.py
- cwas/configuration.py
- cwas/core/annotation/vep.py
- cwas/start.py
Add VEP cache directory option
> Add VEP cache directory option

- cwas/argparser.py
- cwas/configuration.py
- cwas/core/simulation/fastafile.py
- cwas/core/simulation/randomize.py
- cwas/simulation.py
- cwas/start.py
- cwas/utils/check.py
Add random variant generation step
> Add random variant generation step

- cwas/annotation.py
- cwas/argparser.py
- cwas/core/annotation/vep.py
> add multiprocessing option in annotation stage

- cwas/core/simulation/randomize.py
- cwas/simulation.py
> Update random mutation code

- cwas/annotation.py
- cwas/core/annotation/bed.py
add argument for multiprocessing in annotation
> add multiprocessing annotation

- cwas/core/annotation/bed.py
add multiprocessing for the annotation step
> add multiprocessing for annotation step

- cwas/annotation.py
- cwas/categorization.py
Update file extensions for output names.
> Update file extensions for output names

- cwas/annotation.py
Update the output file name with gzipped format
> Update the output file name with gzipped format

- cwas/core/annotation/vep.py
Reverts joonan-lab/cwas#36
There is no `self._num_proc`
> Revert "Make codes for checking paths concise"

- cwas/annotation.py
- cwas/core/annotation/vep.py
1. Unify functions for checking paths
2. Erase some fuctions
> Make codes for checking paths concise

- cwas/effective_num_test.py
- docs/index.rst
Update format of correlation matrix
> Update format of correlation matrix

- cwas/binomial_test.py
- cwas/permutation_test.py
1. Binomial P value calculation
2. Methods for printing and checking arguments
> Improve BurdenTest module

- cwas/argparser.py
- cwas/categorization.py
- cwas/core/categorization/categorizer.py
1. add an option for intersection matrix in argparser
2. functions for generating intersection matrix
3. codes counting the intersections between categories
> Add functions for intersection matrix

- cwas/argparser.py
- cwas/categorization.py
- cwas/core/categorization/categorizer.py
To add codes for generating a covariance matrix directly
> Revert "Add functions for intersection matrix"

- cwas/argparser.py
- cwas/categorization.py
- cwas/core/categorization/categorizer.py
1. add an option for a covariance matrix in argparser
2. functions for generating a covariance matrix
3. codes counting the intersections between categories
> Add functions for a covariance matrix

- cwas/argparser.py
- cwas/categorization.py
- cwas/effective_num_test.py
Add save option for intersection matrix
> Add save option for intersection matrix

- cwas/permutation_test.py
Modify super function in PermutationTest module
> Fix error related to super function

- cwas/categorization.py
- cwas/core/categorization/categorizer.py
1. Change `self.num_proc//3` into `self.num_proc//3 + 1`
2. Use string expression of category as dictionary key instead of category class
3. Introduce a progress bar in Categorizer
> Use string expression of category instead of category class

- cwas/annotation.py
- cwas/argparser.py
- cwas/core/annotation/bed.py
- cwas/core/annotation/vep.py
- cwas/utils/cmd.py
Update annotation process with multiprocessing. Split input VCF and annotate each of them with VEP separately. Then, merge them into a single bgzipped file.
> Update annotation process with multiprocessing

- cwas/argparser.py
- cwas/effective_num_test.py
Change the option num_sim to num_eig
> Update the parameter to set the number of eigen values to use

- cwas/argparser.py
- cwas/binomial_test.py
- cwas/burden_test.py
- cwas/categorization.py
- cwas/permutation_test.py
Add drawing volcano plot in binomial test step, and update cwas step files
> Add drawing volcano plot and update files

- cwas/argparser.py
- cwas/risk_score.py
Add risk score analysis to package
> Add risk score analysis

- cwas/risk_score.py
Add plot function in risk score analysis
> Add plot function in risk score analysis

- cwas/annotation.py
- cwas/argparser.py
- cwas/categorization.py
- cwas/configuration.py
- cwas/core/annotation/vep.py
- cwas/core/categorization/categorizer.py
- cwas/extract_variant.py
- cwas/start.py
- oryx-build-commands.txt
Make CWAS use VCF file to get damaging missense variants
> Make CWAS use VCF file to get damaging missense variants

- cwas/argparser.py
- cwas/burden_shift.py
Update burden_shift.py and argparser.py
> Update burden shift and arguments

- cwas/argparser.py
- cwas/burden_shift.py
- cwas/core/dawn/supernodeWGS.py
Update burden shift and dawn step scripts
> Update burden shift and dawn step scripts

- cwas/categorization.py
Update sample-level correlation matrix calculation
> Update sample-level correlation matrix calculation

- README.md
- cwas/argparser.py
- cwas/burden_test.py
- cwas/permutation_test.py
- cwas/risk_score.py
- docs/quickstart/advanced_tutorial.rst
Pick random cases and pick random training set.
The ratio of the phenotype in the training set should be 1:1.
> Update risk score analysis

- cwas/binomial_test.py
- cwas/burden_test.py
- cwas/risk_score.py
Update binomial_test.py and burden_test.py to add a separator during the load input file.
Update risk_score.py to change how to allocate a fraction of the training and test sets.
> Update binomial_test.py, burden_test.py and risk_score.py

- cwas/burden_test.py
Update category counts info table
> Update category counts info table

- cwas/burden_shift.py
- docs/quickstart/advanced_tutorial.rst
- docs/steps/dawn.rst
Update burdenshift output name and documents
> Update burdenshift output name and documents

- cwas/annotation.py
- cwas/categorization.py
- cwas/core/annotation/bed.py
- cwas/core/categorization/parser.py
- cwas/risk_score.py
Make small files not to be gzipped.
Make large files gzipped.
> Update file format

- cwas/burden_shift.py
- cwas/core/dawn/supernodeWGS.py
- cwas/dawn.py
Discard pseudo-count in burden shift and conflicts in dawn.py
> Update burden_shift.py and dawn.py

- cwas/argparser.py
- cwas/burden_shift.py
- cwas/categorization.py
- cwas/effective_num_test.py
- cwas/extract_variant.py
- cwas/permutation_test.py
- docs/install/installation.rst
- docs/quickstart/advanced_tutorial.rst
- docs/quickstart/quick_tutorial.rst
- Update code to use unzipped input
- Update documents
> Update code to use unzipped input

- cwas/burden_test.py
- cwas/core/categorization/parser.py
- cwas/effective_num_test.py
- cwas/permutation_test.py
- cwas/risk_score.py
Update replacement codes
- Find pattern and replace to create output file name
> Update replacement codes

- cwas/burden_shift.py
- cwas/categorization.py
- cwas/core/categorization/categorizer.py
- cwas/core/categorization/parser.py
- cwas/core/common.py
- pyproject.toml
- setup.py
Enable large scale functional annotations for categorization. Before, large number of functional annotation datasets encountered errors with astype(int). This update fix that.
> Enable large scale annotations

- docs/install/installation.rst
- docs/quickstart/advanced_tutorial.rst
- docs/quickstart/quick_tutorial.rst
- docs/required/input.rst
> Update cwas documents

- cwas/core/dawn/supernodeWGS.py
- cwas/risk_score.py
Fix error in supernodeWGS.py and update dawn.py
> Fix error in dawn process

- cwas/core/categorization/categorizer.py
- cwas/risk_score.py
> Use the same number of training set using 'SET' column from sample information

- cwas/argparser.py
- cwas/effective_num_test.py
- cwas/risk_score.py
Update argparser.py, effective_num_test.py and risk_score.py
> Update argparser.py, effective_num_test.py and risk_score.py

- cwas/categorization.py
Update categorizatio.py to use less memory
> Update categorizatio.py to use less memory

- README.md
- cwas/argparser.py
- cwas/correlation.py
- cwas/risk_score.py
- pyproject.toml
Add options
- `--do_loop`: use each annotation from functional annotation to calculate risk score.
- `--n_of_one_leave`: calculate risk score while excluding one annotation from functional annotation.
> Add N of one leave and each annotation RS loop

- cwas/extract_variant.py
Adjust the code to renewed categorization code and modify the result format as zarr
> Update extract_variant command

- cwas/argparser.py
- cwas/core/dawn/supernodeWGS.py
- cwas/dawn.py
Setting default lambda value (tuning parameter in DAWN analysis) as 5.25.
> Default lambda value as 5.25

- cwas/argparser.py
- cwas/risk_score.py
Update argparser.py and risk_score.py to improve the drawing plot.
> Update for plot of risk score

- docs/quickstart/advanced_tutorial.rst
- docs/quickstart/quick_tutorial.rst
- docs/steps/dawn.rst
- `eig_vec.txt.gz` to `eig_vec.zarr`
> Update documents for DWAN tutorial

- cwas/argparser.py
- cwas/risk_score.py
Choose among 'gene_set', 'functional_annotation', and 'functional_score'.
> Specify categories for feature selection

- cwas/dawn.py
- Add BH adjusted FDR in DAWN result table
- Change result names to 'DAWN.~'
> Add FDR to DAWN table

- cwas/risk_score.py
- Edit x axis title 'R2 (%)'
- Make x axis ticks R2*100
> Update risk score plot

- cwas/core/dawn/supernodeWGS.py
- cwas/dawn.py
> Set seed for HMRF

- cwas/argparser.py
- cwas/dawn.py
- Add leiden clustering option to DAWN
> Update leiden clustering
